version: '3.8'
services:
  copaw:
    image: agentscope-registry.ap-southeast-1.cr.aliyuncs.com/agentscope/copaw:latest
    container_name: copaw
    restart: always
    ports:
      - '8088:8088'
    volumes:
      - $docker-path/copaw/working:/app/working
    
    tty: true
    stdin_open: true