# 内网穿透，可视化管理界面
services:
    lucky:
        image: gdy666/lucky:v2
        container_name: lucky
        volumes:
            - $docker-path/lucky/conf:/app/conf
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
        restart: always