# 开源 AI 知识库系统容器化部署

services:
  maxkb:
    image: registry.fit2cloud.com/maxkb/maxkb
    container_name: maxkb
    ports:
      - "8080:8080"
    volumes:
      - $docker-path/maxkb:/opt/maxkb
    restart: always
    network_mode: bridge
  