# 一个轻量级、可自行托管的备忘录中心，方便您轻松捕捉和分享想法。

services:
  memos:
    image: yr0basrw0s4w2t.xuanyuan.run/neosmemo/memos:stable
    container_name: memos
    ports:
      - 5230:5230
    volumes:
      - $docker-path/memos/data:/var/opt/memos
    tty: true
    stdin_open: true

