# 一个轻量级、可自行托管的备忘录中心，方便您轻松捕捉和分享想法。

services:
  memos:
    image: yr0basrw0s4w2t.xuanyuan.run/neosmemo/memos:stable
    container_name: memos
    ports:
      - 5230:5230
    volumes:
      - /vol1/1000/Docker/memos/data:/var/opt/memos
    tty: true
    stdin_open: true
    labels:
      watchcow.enable: "true"
      watchcow.appname: watchcow.memos
      watchcow.display_name: Memos
      watchcow.desc: 一个轻量级、可自行托管的备忘录中心，方便您轻松捕捉和分享想法。开源，无追踪，永久免费。
      watchcow.version: 1.0.0
      watchcow.maintainer: WatchCow
      watchcow.service_port: "5230"
      watchcow.protocol: http
      watchcow.path: /
      watchcow.ui_type: url
      watchcow.icon: https://s2.loli.net/2026/01/19/H4zQKYnyN2dkTFv.png
