# 音乐标签编辑器
services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8002:8002"
    volumes:
      - /vol1/1000/Music/media:/app/media
      - $docker-path/music_tag_web/config:/app/data
      - /vol1/1000/Music/download:/app/download
    restart: always
    network_mode: bridge  # 添加网络模式确保兼容性