# roocode的本地向量数据库
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - $docker-path/qdrant/storage/:/qdrant/storage
    environment: 
      QDRANT__SERVICE__API_KEY: ""
    tty: true
    stdin_open: true
