# 思源笔记容器化部署
services:
  siyuan:
    container_name: siyuan
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=$name1269367656']
    # user: "${TRIM_UID:-1000}:${TRIM_GID:-1001}"
    ports:
      - 6806:6806
    volumes:
      - /var/apps/docker-siyuan/shares/siyuan/workspace:/siyuan/workspace
      - /var/apps/docker-siyuan/var/config:/.config
    restart: always
    environment:
      - TZ=Etc/UTC
    networks:
      - trim-default

networks:
  trim-default:
    external: true