# Sun Panel 管理面板

services:
  sun-panel:
    image: "hslr/sun-panel:latest"
    container_name: sun-panel
    volumes:
      - $docker-path/sun-panel/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock # 挂载docker.sock
      # - $docker-path/sun-panel/runtime:/app/runtime # 挂载日志目录
      # - /mnt/sata1-1:/os # 硬盘挂载点（根据自己需求修改）
    ports:
      - 3002:3002
    restart: always
    network_mode: bridge  # 添加网络模式确保兼容性
    
    labels:
      # 启用 WatchCow 发现
      watchcow.enable: "true"
      
      # 应用标识
      watchcow.appname: "watchcow.sun-panel"
      watchcow.display_name: "Sun Panel"
      watchcow.desc: "简洁易用的服务器监控与管理面板"
      watchcow.version: "1.0.0"
      watchcow.maintainer: "Runos"
      
      # 网络配置
      watchcow.service_port: "3002"  # 宿主机端口
      watchcow.protocol: "http"
      watchcow.path: "/"
      
      # UI 配置
      watchcow.ui_type: "url"
      watchcow.icon: "https://s2.loli.net/2026/01/15/oGkWIJ8ZhFNpyVm.png"