# 小米音乐 Docker 版 - 音乐播放与管理
services:
  xiaomusic:
    image: hanxi/xiaomusic:latest
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 58090:8090
    environment:
      XIAOMUSIC_PUBLIC_PORT: 58090
    volumes:
      - $docker-path/media/xiaomusic_music:/app/music
      - $docker-path/media/xiaomusic_conf:/app/conf
    network_mode: bridge  # 添加网络模式确保兼容性
